# Generated by Django 5.1.1 on 2024-10-09 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showed_name", models.CharField(blank=True, max_length=255)),
                (
                    "profile_picture_path",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("private", models.BooleanField(default=False)),
                (
                    "following_artists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="following",
                        to="app_rhythmiq.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cover_image_path",
                    models.ImageField(blank=True, null=True, upload_to="songs/"),
                ),
                ("description", models.TextField(blank=True)),
                ("mp3_path", models.FileField(upload_to="songs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.TimeField()),
                ("streaming_numbers", models.IntegerField(default=0)),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="songs", to="app_rhythmiq.userprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cover_image_path",
                    models.ImageField(blank=True, null=True, upload_to="playlists/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("private", models.BooleanField(default=False)),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="app_rhythmiq.song"
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playlists_followed",
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadedSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_downloaded_at", models.DateTimeField(auto_now=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "song")},
            },
        ),
    ]
