# Generated by Django 5.1.1 on 2025-01-25 15:18

import app_rhythmiq.models.playlist
import app_rhythmiq.models.song
import app_rhythmiq.models.user_profile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("showed_name", models.CharField(blank=True, max_length=255)),
                (
                    "profile_picture_path",
                    models.ImageField(
                        blank=True,
                        default="profiles/default_profile_picture.png",
                        null=True,
                        upload_to=app_rhythmiq.models.user_profile.profile_picture_path,
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                (
                    "account_type",
                    models.IntegerField(
                        choices=[(0, "Admin"), (1, "User"), (2, "Artist")], default=0
                    ),
                ),
                (
                    "following_artists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cover_image_path",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_rhythmiq.models.song.cover_image_path,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "song_path",
                    models.FileField(upload_to=app_rhythmiq.models.song.song_file_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField()),
                ("streaming_numbers", models.IntegerField(default=0)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="app_rhythmiq.genre"
                    ),
                ),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="songs", to="app_rhythmiq.userprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cover_image_path",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_rhythmiq.models.playlist.playlist_cover_image_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("private", models.BooleanField(default=False)),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="app_rhythmiq.song"
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playlists_followed",
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "song")},
            },
        ),
        migrations.CreateModel(
            name="DownloadedSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_downloaded_at", models.DateTimeField(auto_now=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_rhythmiq.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "song")},
            },
        ),
    ]
