# Generated by Django 5.1.1 on 2024-11-22 20:00

import app_rhythmiq.models.song
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="cover_image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_rhythmiq.models.song.cover_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="mp3_path",
            field=models.FileField(upload_to=app_rhythmiq.models.song.song_file_path),
        ),
    ]
