# Generated by Django 5.1.1 on 2025-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="showed_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
