# Generated by Django 5.1.1 on 2025-01-01 21:37

import app_rhythmiq.models.playlist
import app_rhythmiq.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0002_alter_song_cover_image_path_alter_song_mp3_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_type",
            field=models.IntegerField(
                choices=[(0, "Admin"), (1, "User"), (2, "Artist")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="cover_image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_rhythmiq.models.playlist.playlist_cover_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following_artists",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="app_rhythmiq.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_rhythmiq.models.user_profile.profile_picture_path,
            ),
        ),
    ]
