# Generated by Django 5.1.1 on 2025-01-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0003_userprofile_account_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="downloadedsong",
            unique_together={("user", "song")},
        ),
    ]
