# Generated by Django 5.1.1 on 2025-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0004_alter_downloadedsong_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="app_rhythmiq.genre"
            ),
        ),
    ]
