# Generated by Django 5.1.1 on 2025-01-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0005_song_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="mp3_path",
            new_name="song_path",
        ),
    ]
