# Generated by Django 5.1.1 on 2025-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0006_rename_mp3_path_song_song_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
