# Generated by Django 5.1.1 on 2025-01-20 22:13

import app_rhythmiq.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rhythmiq", "0007_alter_song_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture_path",
            field=models.ImageField(
                blank=True,
                default="profiles/default_profile_picture.png",
                null=True,
                upload_to=app_rhythmiq.models.user_profile.profile_picture_path,
            ),
        ),
    ]
